---
title: "IBSC School Dashboard"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    vertical_layout: fill
runtime: shiny
resource_files:
- assets/d3.min.js
- assets/forcedirected/binding.js
- assets/forcedirected/fd.js
- assets/forcedirected/repeated-fd.js
- assets/forcedirected/styles.css
---

```{r setup, include=FALSE}
library(tidyverse)
source("C:/Users/jbeng/Documents/IBSCMasterFeedbackDash/assets/R/gatherNodes.R")
source("C:/Users/jbeng/Documents/IBSCMasterFeedbackDash/assets/forcedirected/forcedirected.R")
nodesAmalgam <- gatherNodes()

```

sidebar {.sidebar}
--------------------------------------------------------------------------------

### Input

some text


class level data {data-width=400}
--------------------------------------------------------------------------------

class level data goes here

```{r}
print ("some code output")

```

dataCol {data-width=900}
--------------------------------------------------------------------------------
### parliament graph

```{r}

parliamentOutput("parliament1")
output$parliament1 <- renderParliament(parliament("Hello", nodesAmalgam))

```